[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22.13.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true 